.\" Tristan Le Guern <tleguern@bouledef.eu>
.\"
.\" This file is placed in the public domain.
.\"
.Dd $Mdocdate$
.Dt MARTINESAY 1
.Os
.Sh NAME
.Nm martinesay
.Nd non-configurable thinking jellyfish (and no more)
.Sh SYNOPSIS
.Nm
.Op Fl l
.Op Fl e Cm eyes
.Op Fl f Cm cowfile
.Op Fl T Cm tongue
.Op something
.Sh DESCRIPTION
The
.Nm
utility prints an ASCII picture of a jellyfish thinking
.Ar something .
Jellyfishes are somewhat limited, so complicated thought will be rejected.
This specific jellyfish is named Martine and she lives on the Internet.
You might actually find her in various places.
.Pp
(|€~
.Sh SEE ALSO
.Xr cowsay 1
.Sh AUTHORS
The
.Nm
utility was written by
.An Tristan Le Guern Aq Mt tleguern@bouledef.eu .
