.\" Copyright (c) 2014 Tristan Le Guern <tleguern@bouledef.eu>
.\"
.\" This file is placed in the public domain.
.\"
.Dd $Mdocdate$
.Dt MARTINESAY 1
.Os
.Sh NAME
.Nm martinesay
.Nd non-configurable thinking jellyfish (and no more)
.Sh SYNOPSIS
.Nm
.Ar say
.Sh DESCRIPTION
The
.Nm
utility prints an ASCII picture of a jellyfish thinking something provided by
the user. Jellyfishes are somewhat limited, so complicated thought will be
rejected.
.Sh SEE ALSO
.Xr cowsay 1
